# Change these first
owner: element-gaming # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://element-gaming.eu
    icon: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Web App Network
    url: https://app.element-gaming.eu
    icon: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: API 
    method: GET
    url: https://api.element-gaming.eu   
    headers:
      - "Content-Type: application/json"
    icon: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Telegram Bot 
    method: GET
    url: https://api.element-gaming.eu  
    headers:
      - "Content-Type: application/json"
    icon: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Shortner URL 
    url: https://emt.gg
    icon: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

assignees: # Users to assign downtime issues (optional)
  - andreacw5

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.element-gaming.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
  name: Element Gaming
  favicon: https://app.element-gaming.eu/_nuxt/icons/icon_64x64.c8d5ec.png
  introTitle: Element Gaming Status
  introMessage: This is the status page for Element Gaming services and websites
  theme: dark
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
